### ISSUE TITLE
Is Python >=3.10 really required?

### ISSUE THREAD

**Issue by ctdegroot** [Big-Life-Lab/PHES-ODM-Validation#210]
### Bug Description

Not actually a bug, but didn't know how else to make this request. Is Python >=3.10 really required? I have a project where this is a dependancy so it is forcing my project to require >3.10. Just wondering if this could be dialled back a bit for better compatibility. Thanks

### The operating system on which the bug occured

Mac OS

### Python Version

3.10

**Comment by yulric** [comment]
Hi @ctdegroot, thanks for your issue! We chose this version because of ease (it was the latest version available when we started this project, not a good reason....). We'll look into how far back we can go but it will be at least version 3.x.x. For our information, what version of Python are you using?

**Comment by ctdegroot** [comment]
I was using 3.9 but did upgrade to 3.10 to use this in my code. It would be great if you could go back to 3.8 if possible, since that is what I had set up for my continuous integration pipeline (which now fails due to this dependency). Just wanting to avoid pinning to a newer version for dependency reasons, unless required. Thanks for looking into it :)

**Comment by yulric** [comment]
NVM, after talking to @zargot we're on 3.10 because of the [assertNoLogs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertNoLogs) function. We're going to try to see if we can replace that with something else. Since that's only used for the tests, the library code should theoretically work for versions before 3.10.

**Comment by zargot** [comment]
@ctdegroot, no worries, it's a good enhancement. We're aiming to have it done next week, if not earlier. In the meantime you can try this (work in progress) branch: 210-python-version

**Comment by zargot** [comment]
Forgot to close this. This issue should now be fixed in `dev`. Let us know if there are any more issues, @ctdegroot.
